# 是否开启更新提醒,建议开启
isCheckUpdate: true

# op登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true

# 维护模式提醒
maintenanceModeMsg: "&e服务器正在维护中..."

# MOTD配置 (可自定义无限扩展多组,随机获取一组)
motd:
  # 第一组配置
  yi:
    # 第一行
    motd1: "&b&lFolia服务器&d→→→&4*&e友爱&4*&9团结&4*&6和平&e&l︳&4★&dWelcome&e&4★&e&l︳&d☆&6&l双击&e&l进入&9&l游戏&d☆"
    # 第二行
    motd2: "&4&l游戏版本：&e&l1.19.4  &c请玩家多去论坛交流 &c一起建筑美丽的家~"
  # 第二组配置
  er:
    # 第一行
    motd1: "&b&lFolia服务器&d→→→&4*&e友爱&4*&9团结&4*&6和平&e&l︳&4★&dWelcome&e&4★&e&l︳&d☆&6&l双击&e&l进入&9&l游戏&d☆"
    # 第二行
    motd2: "&4&l游戏版本：&e&l1.19.4   &62023年 全新起航 请务必支持我们~"