name: RiceMotd
main: cn.handyplus.rice.motd.RiceMotd
version: 1.0.1-spigot
author: handy
website: https://ricedoc.handyplus.cn/wiki/RiceMotd/
api-version: 1.13
softdepend: [ PlaceholderAPI ]
description: 米饭MOTD插件
commands:
  riceMotd:
    description: 米饭MOTD插件
permissions:
  riceMotd.*:
    description: 米饭MOTD插件
    children:
      riceMotd.reload: true
  description.reload:
    description: 重载插件
    default: op